import subprocess
import xlwt
import os
value = 106110000
book = xlwt.Workbook()
sheet1 = book.add_sheet("excelsheet")
col1 = sheet1.col(0)
col1.width = 256*40
book.save("result.xls")
temp1 = open("tempfile1","w")
temp1.write("0")
temp1.close()
temp2 = open("tempfile2","w")
temp2.write("0")
temp2.close()
temp10 = open("ten","w")
temp10.write("0")
temp10.close()
temp9 = open("nine","w")
temp9.write("0")
temp9.close()
temp8 = open("eight","w")
temp8.write("0")
temp8.close()
temp7 = open("seven","w")
temp7.write("0")
temp7.close()
temp6 = open("six","w")
temp6.write("0")
temp6.close()
temp5 = open("five","w")
temp5.write("0")
temp5.close()
for j in xrange(1,10):
        newvalue = str(value + j)
        subprocess.call(" python get_result.py "+newvalue, shell=True)
temp1 = open("tempfile1","r")
temp2 = open("tempfile2","r")
no = float(temp1.readline())
total = float(temp2.readline())
avg = total/no
fileavg = open("Statistics.doc","w")
fileavg.write("Average GPA = "+str(avg))
fileavg.write("\n\n")
temp10 = open("ten","r")
temp9 = open("nine","r")
temp8 = open("eight","r")
temp7 = open("seven","r")
temp6 = open("six","r")
temp5 = open("five","r")
fileavg.write("No. of 10 pointers : "+temp10.readline())
fileavg.write("\n")
fileavg.write("No. of 9 pointers : "+temp9.readline())
fileavg.write("\n")
fileavg.write("No. of 8 pointers : "+temp8.readline())
fileavg.write("\n")
fileavg.write("No. of 7 pointers : "+temp7.readline())
fileavg.write("\n")
fileavg.write("No. of 6 pointers : "+temp6.readline())
fileavg.write("\n")
fileavg.write("No. of 5 pointers : "+temp5.readline())
fileavg.close()
temp10.close()
temp9.close()
temp8.close()
temp7.close()
temp6.close()
temp5.close()
os.remove("tempfile1")
os.remove("tempfile2")
os.remove("ten")
os.remove("nine")
os.remove("eight")
os.remove("seven")
os.remove("six")
os.remove("five")
